<?xml version="1.0" encoding="utf-8"?><testsuite errors="2" failures="0" name="pytest" skips="0" tests="2" time="0.246"><testcase classname="" file="test.01.get_packages.tavern.yml" name="test.01.get_packages.tavern.yml" time="0"><error message="collection failure">/home/luis/.local/lib/python2.7/site-packages/tavern/testutils/pytesthook.py:74: in collect
    all_tests = list(yaml.load_all(self.fspath.open(encoding=&quot;utf-8&quot;), Loader=IncludeLoader))
/home/luis/.local/lib/python2.7/site-packages/yaml/__init__.py:83: in load_all
    yield loader.get_data()
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:33: in get_data
    return self.construct_document(self.get_node())
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:48: in construct_document
    for dummy in generator:
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:393: in construct_yaml_seq
    data.extend(self.construct_sequence(node))
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:118: in construct_sequence
    for child in node.value]
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:88: in construct_object
    data = constructor(self, node)
/home/luis/.local/lib/python2.7/site-packages/tavern/util/loader.py:83: in construct_include
    raise BadSchemaError(&quot;Unknown filetype &apos;{}&apos;&quot;.format(filename))
E   BadSchemaError: Unknown filetype &apos;/home/luis/repos/tng-tests/tests/base_tests/environment_file&apos;</error></testcase><testcase classname="" file="test.02.get_admin_logs.tavern.yml" name="test.02.get_admin_logs.tavern.yml" time="0"><error message="collection failure">/home/luis/.local/lib/python2.7/site-packages/tavern/testutils/pytesthook.py:74: in collect
    all_tests = list(yaml.load_all(self.fspath.open(encoding=&quot;utf-8&quot;), Loader=IncludeLoader))
/home/luis/.local/lib/python2.7/site-packages/yaml/__init__.py:83: in load_all
    yield loader.get_data()
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:33: in get_data
    return self.construct_document(self.get_node())
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:48: in construct_document
    for dummy in generator:
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:393: in construct_yaml_seq
    data.extend(self.construct_sequence(node))
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:118: in construct_sequence
    for child in node.value]
/home/luis/.local/lib/python2.7/site-packages/yaml/constructor.py:88: in construct_object
    data = constructor(self, node)
/home/luis/.local/lib/python2.7/site-packages/tavern/util/loader.py:83: in construct_include
    raise BadSchemaError(&quot;Unknown filetype &apos;{}&apos;&quot;.format(filename))
E   BadSchemaError: Unknown filetype &apos;/home/luis/repos/tng-tests/tests/base_tests/environment_file&apos;</error></testcase></testsuite>